services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Causal\Oidc\:
    resource: '../Classes/*'

  Causal\Oidc\EventListener\FrontendLoginEventListener:
    tags:
      - name: event.listener
        identifier: 'causal/oidc'
        method: 'modifyLoginFormView'
        event: TYPO3\CMS\FrontendLogin\Event\ModifyLoginFormViewEvent
